// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVdnobdV1tn1uDeerYS4_PaZHdrZ0sMI',
    appId: '1:18347375518:web:21c72e22ce77c40435348f',
    messagingSenderId: '18347375518',
    projectId: 'moriana-mobile',
    authDomain: 'moriana-mobile.firebaseapp.com',
    storageBucket: 'moriana-mobile.firebasestorage.app',
    measurementId: 'G-VNXWRDYB3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFKfU0yH0SHWZRY_2CXE6m2hchKRZARA',
    appId: '1:18347375518:android:305f654f19c6552735348f',
    messagingSenderId: '18347375518',
    projectId: 'moriana-mobile',
    storageBucket: 'moriana-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTt-jnbzTn8PYsiH5ReG6xaxJwTtUIHg',
    appId: '1:18347375518:ios:1c7ce51067ccc9a335348f',
    messagingSenderId: '18347375518',
    projectId: 'moriana-mobile',
    storageBucket: 'moriana-mobile.firebasestorage.app',
    iosBundleId: 'com.example.morianaMobile',
  );
}
